
'use strict';
const DB_NAME='worth-local-portfolio', DB_VERSION=1;
const STORE_NAMES=['accounts','assets','positions','snapshots'];
const state={accounts:[],assets:[],positions:[],snapshots:[],moneyHidden:false,historyScope:'portfolio'};
let db=null, pendingActions=[];
const $=(sel,root=document)=>root.querySelector(sel), $$=(sel,root=document)=>Array.from(root.querySelectorAll(sel)), byId=id=>document.getElementById(id);
const palette=['#17181b','#5667ff','#9b63e8','#21c26b','#f5a341','#33bfc6','#ee5264','#7a8395'];
const usd=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
const numberFmt=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:8});
function money(v){return usd.format(Number(v)||0)} function number(v){return numberFmt.format(Number(v)||0)}
function uid(){return crypto.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function initials(v=''){return String(v).trim().slice(0,2).toUpperCase()||'•'} function colorFor(id=''){let s=0;for(const c of id)s=(s+c.charCodeAt(0))%palette.length;return palette[s]}
function openDatabase(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{for(const n of STORE_NAMES)if(!r.result.objectStoreNames.contains(n))r.result.createObjectStore(n,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);r.onblocked=()=>rej(new Error('IndexedDB blocked'))})}
function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)} function dbAll(n){return new Promise((res,rej)=>{const r=store(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})} function dbPut(n,v){return new Promise((res,rej)=>{const r=store(n,'readwrite').put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})} function dbDelete(n,id){return new Promise((res,rej)=>{const r=store(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})} function dbClear(n){return new Promise((res,rej)=>{const r=store(n,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function reload(){for(const n of STORE_NAMES)state[n]=await dbAll(n);state.accounts.sort((a,b)=>a.name.localeCompare(b.name,'ru'));state.assets.sort((a,b)=>a.symbol.localeCompare(b.symbol,'ru'));state.snapshots.sort((a,b)=>a.createdAt-b.createdAt);renderAll()}
function assetBy(id){return state.assets.find(x=>x.id===id)} function accountBy(id){return state.accounts.find(x=>x.id===id)}
function positionValue(p){return WorthCore.positionValue(p,state.assets)} function portfolioTotal(){return WorthCore.portfolioTotal(state.positions,state.assets)} function assetQuantity(id){return WorthCore.assetQuantity(id,state.positions)} function assetTotal(id){return WorthCore.assetTotal(id,state.positions,state.assets)} function accountTotal(id){return WorthCore.accountTotal(id,state.positions,state.assets)} function visibleMoney(v){return state.moneyHidden?'••••••':money(v)}
function renderAll(){renderBalance();renderAllocation();renderAccounts();renderAssets();renderPositions();refreshHistoryScope();renderHistory();refreshPositionForm()}
function renderBalance(){const total=portfolioTotal(), el=byId('homeTitle'),delta=byId('balanceDelta'),last=state.snapshots.at(-1);el.textContent=visibleMoney(total);if(!last){delta.textContent='Сохраните первый снимок';delta.style.color='';return}const diff=total-Number(last.total||0),pct=last.total?diff/Math.abs(last.total)*100:0;if(Math.abs(diff)<.005){delta.textContent='Без изменений с последнего снимка';delta.style.color='';return}delta.textContent=`${diff>0?'+':'−'}${state.moneyHidden?'••••':money(Math.abs(diff))} · ${diff>0?'+':'−'}${Math.abs(pct).toFixed(1)}%`;delta.style.color=diff>0?'var(--green)':'var(--red)'}
function renderAllocation(){const rows=state.assets.map(asset=>({asset,value:assetTotal(asset.id),qty:assetQuantity(asset.id)})).filter(x=>x.value!==0).sort((a,b)=>b.value-a.value),gross=rows.reduce((s,x)=>s+Math.abs(x.value),0),bar=byId('allocationBar'),list=byId('allocationList');byId('assetsCount').textContent=`${rows.length} ${decl(rows.length,'актив','актива','активов')}`;if(!rows.length||gross===0){bar.innerHTML='';list.innerHTML='<div class="empty-state">Добавьте счёт, актив и первый остаток — здесь появится структура портфеля.</div>';return}bar.innerHTML=rows.map(x=>`<span class="allocation-segment" style="width:${Math.abs(x.value)/gross*100}%;background:${colorFor(x.asset.id)}"></span>`).join('');list.innerHTML=rows.slice(0,6).map(x=>`<div class="allocation-row"><span class="asset-badge" style="background:${colorFor(x.asset.id)}">${escapeHTML(initials(x.asset.symbol))}</span><div class="allocation-meta"><strong>${escapeHTML(x.asset.symbol)}</strong><small>${number(x.qty)} · ${(Math.abs(x.value)/gross*100).toFixed(1)}%</small></div><div class="allocation-value"><strong>${visibleMoney(x.value)}</strong><small>${visibleMoney(x.asset.price)} / ед.</small></div></div>`).join('')}
function renderAccounts(){const list=byId('accountsList');if(!state.accounts.length){list.innerHTML='<div class="empty-state">Например: Наличные, банк, биржа или деньги, которые вам должны.</div>';return}list.innerHTML=state.accounts.map(a=>`<div class="list-card"><div class="list-icon">${accountGlyph(a.type)}</div><div class="list-main"><strong>${escapeHTML(a.name)}</strong><small>${escapeHTML(a.type)} · ${state.positions.filter(p=>p.accountId===a.id).length} поз.</small></div><div class="list-value"><strong>${visibleMoney(accountTotal(a.id))}</strong></div><button class="menu-button" data-account-menu="${a.id}" aria-label="Действия со счётом">···</button></div>`).join('')}
function renderAssets(){const list=byId('assetsList');if(!state.assets.length){list.innerHTML='<div class="empty-state">Актив — это валюта, металл, криптовалюта, акция или другое имущество с ценой в долларах.</div>';return}list.innerHTML=state.assets.map(a=>`<div class="list-card"><div class="list-icon" style="background:${colorFor(a.id)};color:#fff">${escapeHTML(initials(a.symbol))}</div><div class="list-main"><strong>${escapeHTML(a.symbol)} · ${escapeHTML(a.name)}</strong><small>${number(assetQuantity(a.id))} ед. · ${visibleMoney(a.price)} / ед.</small></div><div class="list-value"><strong>${visibleMoney(assetTotal(a.id))}</strong></div><button class="menu-button" data-asset-menu="${a.id}" aria-label="Действия с активом">···</button></div>`).join('')}
function renderPositions(){const summary=byId('positionsSummary'),list=byId('positionsList');summary.innerHTML=state.accounts.map(a=>`<div class="summary-pill"><small>${escapeHTML(a.name)}</small><strong>${visibleMoney(accountTotal(a.id))}</strong></div>`).join('');if(!state.positions.length){list.innerHTML='<div class="empty-state">Позиция связывает актив со счётом и хранит его количество.</div>';return}list.innerHTML=state.positions.slice().sort((a,b)=>positionValue(b)-positionValue(a)).map(p=>{const a=assetBy(p.assetId),acc=accountBy(p.accountId);return `<div class="list-card"><div class="list-icon" style="background:${colorFor(a?.id||'x')};color:#fff">${escapeHTML(initials(a?.symbol))}</div><div class="list-main"><strong>${escapeHTML(a?.symbol||'Удалённый актив')}</strong><small>${escapeHTML(acc?.name||'Удалённый счёт')} · ${number(p.quantity)} ед.</small></div><div class="list-value"><strong>${visibleMoney(positionValue(p))}</strong><small>${a?visibleMoney(a.price):'—'} / ед.</small></div><button class="menu-button" data-position-menu="${p.id}" aria-label="Действия с позицией">···</button></div>`}).join('')}
function refreshHistoryScope(){const select=byId('historyScope'),current=state.historyScope;select.innerHTML='<option value="portfolio">Весь портфель</option>'+state.accounts.map(a=>`<option value="account:${a.id}">${escapeHTML(a.name)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;else{state.historyScope='portfolio';select.value='portfolio'}}
function historyData(){if(state.historyScope==='portfolio')return state.snapshots.map(s=>({snapshot:s,value:Number(s.total)||0}));const id=state.historyScope.slice(8);return state.snapshots.map(s=>{const rec=Array.isArray(s.accounts)?s.accounts.find(a=>a.accountId===id):null;return rec?{snapshot:s,value:Number(rec.total)||0}:null}).filter(Boolean)}
function renderHistory(){const list=byId('historyList'),data=historyData(),isAccount=state.historyScope!=='portfolio';byId('historyRangeLabel').textContent=isAccount?(accountBy(state.historyScope.slice(8))?.name||'Счёт'):'Весь портфель';if(!data.length){list.innerHTML=`<div class="empty-state">${isAccount?'Для этого счёта пока нет совместимых снимков. Сделайте новый снимок после обновления приложения.':'Снимок фиксирует стоимость портфеля на выбранный момент. Делайте их регулярно, чтобы видеть динамику.'}</div>`}else{list.innerHTML=data.slice().reverse().map((item,reverseIndex,arr)=>{const chronologicalIndex=data.findIndex(x=>x.snapshot.id===item.snapshot.id),prev=data[chronologicalIndex-1],diff=prev?item.value-prev.value:null;return `<div class="list-card"><span class="history-dot"></span><div class="list-main"><strong>${formatDate(item.snapshot.createdAt)}</strong><small>${formatTime(item.snapshot.createdAt)}${diff===null?' · первый снимок':` · ${diff>=0?'+':'−'}${state.moneyHidden?'••••':money(Math.abs(diff))}`}</small></div><div class="list-value"><strong>${visibleMoney(item.value)}</strong></div><button class="menu-button" data-snapshot-menu="${item.snapshot.id}" aria-label="Действия со снимком">···</button></div>`}).join('')}drawChart()}
function drawChart(){const canvas=byId('historyChart'),empty=byId('historyEmpty'),dateRow=byId('chartDates'),change=byId('historyChange'),data=historyData();if(data.length<2){empty.classList.remove('hidden');dateRow.children[0].textContent='';dateRow.children[1].textContent='';change.textContent='—';return}empty.classList.add('hidden');const rect=canvas.getBoundingClientRect();if(rect.width<20)return;const dpr=Math.min(devicePixelRatio||1,3),w=rect.width,h=220;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const vals=data.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||Math.max(Math.abs(max),1),padX=4,padY=23,pts=vals.map((v,i)=>({x:padX+i*(w-padX*2)/(vals.length-1),y:padY+(max-v)/range*(h-padY*2)})),diff=vals.at(-1)-vals[0],pct=vals[0]?diff/Math.abs(vals[0])*100:0;const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'rgba(33,194,107,.20)');grad.addColorStop(1,'rgba(33,194,107,0)');ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineTo(pts.at(-1).x,h-padY);ctx.lineTo(pts[0].x,h-padY);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=diff>=0?'#21c26b':'#ee5264';ctx.lineWidth=2.6;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();change.textContent=`${diff>=0?'+':'−'}${state.moneyHidden?'••••':money(Math.abs(diff))} · ${diff>=0?'+':'−'}${Math.abs(pct).toFixed(1)}%`;change.style.color=diff>=0?'var(--green)':'var(--red)';dateRow.children[0].textContent=shortDate(data[0].snapshot.createdAt);dateRow.children[1].textContent=shortDate(data.at(-1).snapshot.createdAt)}
function refreshPositionForm(){const f=byId('positionForm');f.elements.accountId.innerHTML=state.accounts.map(a=>`<option value="${a.id}">${escapeHTML(a.name)}</option>`).join('');f.elements.assetId.innerHTML=state.assets.map(a=>`<option value="${a.id}">${escapeHTML(a.symbol)} · ${escapeHTML(a.name)}</option>`).join('');const disabled=!state.accounts.length||!state.assets.length;byId('positionPrerequisite').classList.toggle('hidden',!disabled);f.querySelector('.sheet-primary').disabled=disabled}
function decl(n,o,f,m){const x=Math.abs(n)%100,y=x%10;if(x>10&&x<20)return m;if(y>1&&y<5)return f;if(y===1)return o;return m} function accountGlyph(t=''){if(t.includes('Банк'))return '▥';if(t.includes('Бирж'))return '↗';if(t.includes('Долг'))return '↔';if(t.includes('Крипто'))return '◇';if(t.includes('Налич'))return '$';return '•'}
function formatDate(ts){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(ts))} function shortDate(ts){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(ts))} function formatTime(ts){return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
function toast(t){const el=byId('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)} function closeDialog(id){const d=byId(id);if(d?.open)d.close()} function openDialog(id){if(id==='positionModal')resetPositionForm();const d=byId(id);if(d&&!d.open)d.showModal()} function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.nav===id));scrollTo({top:0,behavior:'instant'});if(id==='historyView')requestAnimationFrame(drawChart)} function resetPositionForm(){const f=byId('positionForm');f.reset();delete f.dataset.editId;byId('positionModeLabel').textContent='Новая';refreshPositionForm()}
function showActionMenu(title,actions){pendingActions=actions;byId('actionMenuTitle').textContent=title;byId('actionMenuItems').innerHTML=actions.map((a,i)=>`<button type="button" class="action-item ${a.danger?'danger':''}" data-action-index="${i}">${escapeHTML(a.label)}</button>`).join('');openDialog('actionMenuModal')}
async function saveSnapshot(){await dbPut('snapshots',{id:uid(),createdAt:Date.now(),total:portfolioTotal(),accounts:state.accounts.map(a=>({accountId:a.id,name:a.name,total:accountTotal(a.id)})),assets:state.assets.map(a=>({assetId:a.id,symbol:a.symbol,price:Number(a.price),quantity:assetQuantity(a.id),value:assetTotal(a.id)}))});await reload();toast('Снимок сохранён')}
function accountMenu(id){const a=accountBy(id);if(!a)return;showActionMenu(a.name,[{label:'Изменить название',run:()=>{const f=byId('accountEditForm');f.elements.accountId.value=a.id;f.elements.name.value=a.name;openDialog('accountEditModal')}},{label:'Показать историю счёта',run:()=>{state.historyScope=`account:${a.id}`;navigate('historyView');refreshHistoryScope();renderHistory()}},{label:'Удалить счёт',danger:true,run:async()=>{if(!confirm(`Удалить счёт «${a.name}» и все позиции на нём?`))return;for(const p of state.positions.filter(p=>p.accountId===id))await dbDelete('positions',p.id);await dbDelete('accounts',id);await reload();toast('Счёт удалён')}}])}
function assetMenu(id){const a=assetBy(id);if(!a)return;showActionMenu(`${a.symbol} · ${a.name}`,[{label:'Изменить цену',run:()=>{const f=byId('priceForm');f.elements.assetId.value=a.id;f.elements.price.value=a.price;byId('priceAssetTitle').textContent=`${a.symbol} · ${a.name}`;openDialog('priceModal')}},{label:'Удалить актив',danger:true,run:async()=>{if(!confirm(`Удалить ${a.symbol} и все позиции с этим активом?`))return;for(const p of state.positions.filter(p=>p.assetId===id))await dbDelete('positions',p.id);await dbDelete('assets',id);await reload();toast('Актив удалён')}}])}
function positionMenu(id){const p=state.positions.find(x=>x.id===id),a=p&&assetBy(p.assetId);if(!p)return;showActionMenu(a?.symbol||'Позиция',[{label:'Изменить позицию',run:()=>{openDialog('positionModal');const f=byId('positionForm');f.dataset.editId=p.id;f.elements.accountId.value=p.accountId;f.elements.assetId.value=p.assetId;f.elements.quantity.value=p.quantity;byId('positionModeLabel').textContent='Редактирование'}},{label:'Удалить позицию',danger:true,run:async()=>{if(!confirm('Удалить эту позицию?'))return;await dbDelete('positions',id);await reload();toast('Позиция удалена')}}])}
function snapshotMenu(id){showActionMenu('Снимок',[{label:'Удалить снимок',danger:true,run:async()=>{if(!confirm('Удалить этот снимок из истории?'))return;await dbDelete('snapshots',id);await reload();toast('Снимок удалён')}}])}
function renderQuickUpdate(){const c=byId('quickUpdateFields');if(!state.assets.length){c.innerHTML='<div class="empty-state">Сначала добавьте активы.</div>';return}c.innerHTML=state.assets.map(a=>{const fields=state.positions.filter(p=>p.assetId===a.id).map(p=>`<div class="update-input"><label>${escapeHTML(accountBy(p.accountId)?.name||'Счёт')} · количество</label><input type="number" step="any" inputmode="decimal" data-position-qty="${p.id}" value="${p.quantity}"></div>`).join('');return `<div class="update-group"><div class="update-group-head"><strong>${escapeHTML(a.symbol)} · ${escapeHTML(a.name)}</strong><small>${visibleMoney(assetTotal(a.id))}</small></div><div class="update-grid"><div class="update-input"><label>Цена, $</label><input type="number" min="0" step="any" inputmode="decimal" data-asset-price="${a.id}" value="${a.price}"></div>${fields}</div></div>`}).join('')}
function exportData(){const payload={app:'Worth',version:2,baseCurrency:'USD',exportedAt:new Date().toISOString(),accounts:state.accounts,assets:state.assets,positions:state.positions,snapshots:state.snapshots},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`worth-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Резервная копия создана')} function validateImport(data){return WorthCore.validateImport(data)} async function importData(file){try{const data=JSON.parse(await file.text());validateImport(data);if(!confirm('Импорт полностью заменит текущие локальные данные. Продолжить?'))return;for(const n of STORE_NAMES){await dbClear(n);for(const item of data[n])await dbPut(n,item)}await reload();toast('Данные восстановлены')}catch(e){console.error(e);alert('Не удалось импортировать резервную копию. Файл повреждён или имеет неподдерживаемый формат.')}}
function bindEvents(){document.addEventListener('click',async e=>{const open=e.target.closest('[data-open]');if(open){openDialog(open.dataset.open);return}const close=e.target.closest('[data-close]');if(close){closeDialog(close.dataset.close);return}const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);return}const am=e.target.closest('[data-account-menu]');if(am){accountMenu(am.dataset.accountMenu);return}const asm=e.target.closest('[data-asset-menu]');if(asm){assetMenu(asm.dataset.assetMenu);return}const pm=e.target.closest('[data-position-menu]');if(pm){positionMenu(pm.dataset.positionMenu);return}const sm=e.target.closest('[data-snapshot-menu]');if(sm){snapshotMenu(sm.dataset.snapshotMenu);return}const ai=e.target.closest('[data-action-index]');if(ai){const action=pendingActions[Number(ai.dataset.actionIndex)];closeDialog('actionMenuModal');if(action)await action.run();return}});
byId('historyScope').addEventListener('change',e=>{state.historyScope=e.target.value;renderHistory()});byId('privacyToggle').addEventListener('click',()=>{state.moneyHidden=!state.moneyHidden;renderAll()});byId('saveSnapshotBtn').addEventListener('click',saveSnapshot);byId('saveSnapshotBtnHistory').addEventListener('click',saveSnapshot);byId('openQuickUpdate').addEventListener('click',()=>{renderQuickUpdate();openDialog('quickUpdateModal')});byId('backupShortcut').addEventListener('click',()=>navigate('dataView'));byId('exportBtn').addEventListener('click',exportData);byId('importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)await importData(f);e.target.value=''});byId('resetBtn').addEventListener('click',async()=>{if(!confirm('Удалить все счета, активы, позиции и историю с этого устройства?'))return;for(const n of STORE_NAMES)await dbClear(n);await reload();toast('Все данные удалены')});
byId('accountForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,name=f.elements.name.value.trim();if(!name)return;await dbPut('accounts',{id:uid(),name,type:f.elements.type.value,createdAt:Date.now()});f.reset();closeDialog('accountModal');await reload();toast('Счёт создан')});byId('accountEditForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,a=accountBy(f.elements.accountId.value),name=f.elements.name.value.trim();if(!a||!name)return;a.name=name;a.updatedAt=Date.now();await dbPut('accounts',a);closeDialog('accountEditModal');await reload();toast('Название изменено')});
byId('assetForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,name=f.elements.name.value.trim(),symbol=f.elements.symbol.value.trim().toUpperCase(),price=Number(f.elements.price.value);if(!name||!symbol||!Number.isFinite(price)||price<0)return;if(state.assets.some(a=>a.symbol.toUpperCase()===symbol)){alert('Актив с таким тикером уже существует.');return}await dbPut('assets',{id:uid(),name,symbol,price,createdAt:Date.now(),updatedAt:Date.now()});f.reset();closeDialog('assetModal');await reload();toast('Актив создан')});
byId('positionForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!state.accounts.length||!state.assets.length)return;const q=Number(f.elements.quantity.value),accountId=f.elements.accountId.value,assetId=f.elements.assetId.value,editId=f.dataset.editId;if(!Number.isFinite(q))return;const dup=state.positions.find(p=>p.accountId===accountId&&p.assetId===assetId&&p.id!==editId);if(dup&&!editId){dup.quantity=q;dup.updatedAt=Date.now();await dbPut('positions',dup)}else await dbPut('positions',{id:editId||uid(),accountId,assetId,quantity:q,createdAt:state.positions.find(p=>p.id===editId)?.createdAt||Date.now(),updatedAt:Date.now()});closeDialog('positionModal');resetPositionForm();await reload();toast('Позиция сохранена')});
byId('priceForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,a=assetBy(f.elements.assetId.value),price=Number(f.elements.price.value);if(!a||!Number.isFinite(price)||price<0)return;a.price=price;a.updatedAt=Date.now();await dbPut('assets',a);closeDialog('priceModal');await reload();toast('Цена обновлена')});byId('quickUpdateForm').addEventListener('submit',async e=>{e.preventDefault();for(const i of $$('[data-asset-price]',e.currentTarget)){const a=assetBy(i.dataset.assetPrice),v=Number(i.value);if(a&&Number.isFinite(v)&&v>=0){a.price=v;a.updatedAt=Date.now();await dbPut('assets',a)}}for(const i of $$('[data-position-qty]',e.currentTarget)){const p=state.positions.find(x=>x.id===i.dataset.positionQty),v=Number(i.value);if(p&&Number.isFinite(v)){p.quantity=v;p.updatedAt=Date.now();await dbPut('positions',p)}}closeDialog('quickUpdateModal');await reload();toast('Портфель обновлён')});window.addEventListener('resize',()=>{if(byId('historyView').classList.contains('active'))drawChart()},{passive:true})}
async function init(){try{db=await openDatabase();bindEvents();await reload();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn))}catch(e){console.error(e);document.body.innerHTML='<div style="padding:30px;font-family:-apple-system">Не удалось открыть локальную базу данных. Проверьте, что Safari разрешает хранение данных для этого сайта.</div>'}} init();
